name: Data Tracker - Docker
on: [push]
jobs:
  my_job: 
    runs-on: ubuntu-latest
    container: 
      image: rocker/tidyverse
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Track Data
        run: Rscript data-tracker.R
      - name: Commit results
        run: |
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}
          git add data/
          git commit data/* -m 'Update data' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"    
      - name: Register Data
        run: Rscript register.R

## remarkably(?), we can use the standard checkout action, actions/checkout@v1
## even inside this Docker container.

