name: Data Tracker - Docker
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 0' # Weekly, Sunday midnight

jobs:
  my_job: 
    runs-on: ubuntu-latest
    container: 
      image: rocker/tidyverse
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: git config
        run: |
          git config user.name data-robot
          git config user.email data-robot
      - name: Track Data
        run: Rscript data-tracker.R
      - name: Upload Data Cache
        run: |
          git add store/data
          git commit -m 'Update data [ci skip]' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"    
      - name: Register Data URLs
        run: Rscript register.R
      - name: Upload local registry
        run: |
          git add store
          git commit -m 'Update registry [ci skip]' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"    

## remarkably(?), we can use the standard checkout action, actions/checkout@v1
## even inside this Docker container.

